
/*<auto-generated>
***End of Global definition area***
Changes to this comment may cause incorrect behavior during document based import.
</auto-generated>*/
export function Logging() {

  function val(v) { return (v === undefined || v === null) ? "" : v; }

  let v01 = val(Tags("Analogica_Scalatura_InMax_Leggi_Ai").Read());
  let v02 = val(Tags("Analogica_Scalatura_InMin_Leggi_Ai").Read());
  let v03 = val(Tags("Analogica_Scalatura_MassimoValoreEW_Ai").Read());
  let v04 = val(Tags("Analogica_Scalatura_MinimoValoreEW_Ai").Read());
  let v05 = val(Tags("Analogica_Scalatura_OutMax_Ai").Read());
  let v06 = val(Tags("Analogica_Scalatura_OutMin_Ai").Read());
  let v07 = val(Tags("Analogica_Prm_IsteresiIntMax_Ai").Read());
  let v08 = val(Tags("Analogica_Prm_IsteresiIntMin_Ai").Read());
  let v09 = val(Tags("Analogica_Prm_IsteresiMax_Ai").Read());
  let v10 = val(Tags("Analogica_Prm_IsteresiMin_Ai").Read());
  let v11 = val(Tags("Analogica_Prm_RitOff_ActualIntMax_Ai").Read());
  let v12 = val(Tags("Analogica_Prm_RitOff_ActualIntMin_Ai").Read());
  let v13 = val(Tags("Analogica_Prm_RitOff_ActualMax_Ai").Read());
  let v14 = val(Tags("Analogica_Prm_RitOff_ActualMin_Ai").Read());
  let v15 = val(Tags("Analogica_Prm_RitOff_AllarmeIntMax_Ai").Read());
  let v16 = val(Tags("Analogica_Prm_RitOff_AllarmeIntMin_Ai").Read());
  let v17 = val(Tags("Analogica_Prm_RitOff_AllarmeMax_Ai").Read());
  let v18 = val(Tags("Analogica_Prm_RitOff_AllarmeMin_Ai").Read());
  let v19 = val(Tags("Analogica_Prm_RitOn_ActualIntMax_Ai").Read());
  let v20 = val(Tags("Analogica_Prm_RitOn_ActualIntMin_Ai").Read());
  let v21 = val(Tags("Analogica_Prm_RitOn_ActualMax_Ai").Read());
  let v22 = val(Tags("Analogica_Prm_RitOn_ActualMin_Ai").Read());
  let v23 = val(Tags("Analogica_Prm_RitOn_AllarmeIntMax_Ai").Read());
  let v24 = val(Tags("Analogica_Prm_RitOn_AllarmeIntMin_Ai").Read());
  let v25 = val(Tags("Analogica_Prm_RitOn_AllarmeMax_Ai").Read());
  let v26 = val(Tags("Analogica_Prm_RitOn_AllarmeMin_Ai").Read());
  let v27 = val(Tags("Analogica_Prm_SogliaIntMax_Ai").Read());
  let v28 = val(Tags("Analogica_Prm_SogliaIntMin_Ai").Read());
  let v29 = val(Tags("Analogica_Prm_SogliaMax_Ai").Read());
  let v30 = val(Tags("Analogica_Prm_SogliaMin_Ai").Read());
  let v31 = val(Tags("Analogica_Prm_TipoIngressoanalogico_Ai").Read());
  let v32 = val(Tags("Analogica_Hmi_AbilitaSogliaIntMax_Ai").Read());
  let v33 = val(Tags("Analogica_Hmi_AbilitaSogliaIntMin_Ai").Read());
  let v34 = val(Tags("Analogica_Hmi_AbilitaSogliaMax_Ai").Read());
  let v35 = val(Tags("Analogica_Hmi_AbilitaSogliaMin_Ai").Read());
  let v36 = val(Tags("Analogica_Hmi_NomeSoglia_IntMax_Ai").Read());
  let v37 = val(Tags("Analogica_Hmi_NomeSoglia_IntMin_Ai").Read());
  let v38 = val(Tags("Analogica_Hmi_NomeSoglia_Max_Ai").Read());
  let v39 = val(Tags("Analogica_Hmi_NomeSoglia_Min_Ai").Read());
  let v40 = val(Tags("Analogica_Hmi_ParataPresente_Ai").Read());
  let v41 = val(Tags("Analogica_Hmi_SimulazioneAnalogica_AbilitaTimeout_Ai").Read());
  let v42 = val(Tags("Analogica_Hmi_SimulazioneAnalogica_Attiva_Ai").Read());
  let v43 = val(Tags("Analogica_Hmi_SimulazioneAnalogica_TimeoutTrascorso_Ai").Read());
  let v44 = val(Tags("Analogica_Hmi_SimulazioneAnalogica_TimeoutPreset_Ai").Read());
  let v45 = val(Tags("Analogica_Hmi_SimulazioneAnalogica_Valore_Ai").Read());
  let v46 = val(Tags("Analogica_Allarmi_AbilitaSegnalazioneHMI_IntMax_Ai").Read());
  let v47 = val(Tags("Analogica_Allarmi_AbilitaSegnalazioneHMI_IntMin_Ai").Read());
  let v48 = val(Tags("Analogica_Allarmi_AbilitaSegnalazioneHMI_Maxi_Ai").Read());
  let v49 = val(Tags("Analogica_Allarmi_AbilitaSegnalazioneHMI_Mini_Ai").Read());
  let v50 = val(Tags("Analogica_Allarmi_AbilitaSegnalazioneHMI_OutOfRange_Ai").Read());
  let v51 = val(Tags("Analogica_Allarmi_AbilitaStatoAllarmeMin_Ai").Read());
  let v52 = val(Tags("Analogica_Allarmi_AbilitaStatoAllarmeOutOfRange_Ai").Read());
  let v53 = val(Tags("Analogica_Allarmi_AllarmeDirezioneAllarme_IntMin_Ai").Read());
  let v54 = val(Tags("Analogica_Allarmi_AllarmeDirezioneAllarme_Maxi_Ai").Read());
  let v55 = val(Tags("Analogica_Allarmi_AllarmeDirezioneAllarme_Mini_Ai").Read());
  let v56 = val(Tags("Analogica_Allarmi_AllarmeEnCadCiclo_IntMax_Ai").Read());
  let v57 = val(Tags("Analogica_Allarmi_AllarmeEnCadCiclo_IntMin_Ai").Read());
  let v58 = val(Tags("Analogica_Allarmi_AllarmeEnCadCiclo_Maxi_Ai").Read());
  let v59 = val(Tags("Analogica_Allarmi_AllarmeEnCadCiclo_Mini_Ai").Read());
  let v60 = val(Tags("Analogica_Allarmi_AllarmeLivelloIntMax_Ai").Read());
  let v61 = val(Tags("Analogica_Allarmi_AllarmeLivelloIntMin_Ai").Read());
  let v62 = val(Tags("Analogica_Allarmi_AllarmeLivelloMax_Ai").Read());
  let v63 = val(Tags("Analogica_Allarmi_AllarmeLivelloMin_Ai").Read());
  let v64 = val(Tags("Analogica_Allarmi_AllarmeModoResetAllarmeIntmax_Ai").Read());
  let v65 = val(Tags("Analogica_Allarmi_AllarmeModoResetAllarmeIntmin_Ai").Read());
  let v66 = val(Tags("Analogica_Allarmi_AllarmeModoResetAllarmeMaxi_Ai").Read());
  let v67 = val(Tags("Analogica_Allarmi_AllarmeModoResetAllarmeMini_Ai").Read());
  let v68 = val(Tags("Analogica_Allarmi_OutOfRangeAllarmiBT_Ai").Read());
  let v69 = val(Tags("Analogica_Out_IntmaxAllarmiBT_Ai").Read());
  let v70 = val(Tags("Analogica_Out_IntminAllarmiBT_Ai").Read());
  let v71 = val(Tags("Analogica_Out_MaxAllarmiBT_Ai").Read());
  let v72 = val(Tags("Analogica_Out_MinAllarmiBT_Ai").Read());
  let v73 = val(Tags("Analogica_Rif_Attuale_AI_Valore").Read());
  let v74 = val(Tags("Analogica_Rif_Inc_KpIngiresso_Ai").Read());
  let v75 = val(Tags("Analogica_Rif_Inc_KpParata_Ai").Read());
  let v76 = val(Tags("Analogica_Rif_Inc_Kpid_Ingresso_Ai").Read());
  let v77 = val(Tags("Analogica_Rif_Inc_Kpid_Uscita_Ai").Read());
  let v78 = val(Tags("Analogica_Rif_Inc_Ktrend_Ai").Read());
  let v79 = val(Tags("Index_analogica_Ai").Read());

  HMIRuntime.Trace("Passato dallo script - lettura singola 79 tag");

  const now = new Date();
  const pad2 = function (n) { return (n < 10 ? "0" : "") + n; };
  const timestamp =
    now.getFullYear().toString() +
    pad2(now.getMonth() + 1) +
    pad2(now.getDate()) +
    "_" +
    pad2(now.getHours()) +
    pad2(now.getMinutes()) +
    pad2(now.getSeconds());

  const separator = ";";
  const header = "Timestamp" + separator +
    "Analogica_Scalatura_InMax_Leggi_Ai" + separator +
    "Analogica_Scalatura_InMin_Leggi_Ai" + separator +
    "Analogica_Scalatura_MassimoValoreEW_Ai" + separator +
    "Analogica_Scalatura_MinimoValoreEW_Ai" + separator +
    "Analogica_Scalatura_OutMax_Ai" + separator +
    "Analogica_Scalatura_OutMin_Ai" + separator +
    "Analogica_Prm_IsteresiIntMax_Ai" + separator +
    "Analogica_Prm_IsteresiIntMin_Ai" + separator +
    "Analogica_Prm_IsteresiMax_Ai" + separator +
    "Analogica_Prm_IsteresiMin_Ai" + separator +
    "Analogica_Prm_RitOff_ActualIntMax_Ai" + separator +
    "Analogica_Prm_RitOff_ActualIntMin_Ai" + separator +
    "Analogica_Prm_RitOff_ActualMax_Ai" + separator +
    "Analogica_Prm_RitOff_ActualMin_Ai" + separator +
    "Analogica_Prm_RitOff_AllarmeIntMax_Ai" + separator +
    "Analogica_Prm_RitOff_AllarmeIntMin_Ai" + separator +
    "Analogica_Prm_RitOff_AllarmeMax_Ai" + separator +
    "Analogica_Prm_RitOff_AllarmeMin_Ai" + separator +
    "Analogica_Prm_RitOn_ActualIntMax_Ai" + separator +
    "Analogica_Prm_RitOn_ActualIntMin_Ai" + separator +
    "Analogica_Prm_RitOn_ActualMax_Ai" + separator +
    "Analogica_Prm_RitOn_ActualMin_Ai" + separator +
    "Analogica_Prm_RitOn_AllarmeIntMax_Ai" + separator +
    "Analogica_Prm_RitOn_AllarmeIntMin_Ai" + separator +
    "Analogica_Prm_RitOn_AllarmeMax_Ai" + separator +
    "Analogica_Prm_RitOn_AllarmeMin_Ai" + separator +
    "Analogica_Prm_SogliaIntMax_Ai" + separator +
    "Analogica_Prm_SogliaIntMin_Ai" + separator +
    "Analogica_Prm_SogliaMax_Ai" + separator +
    "Analogica_Prm_SogliaMin_Ai" + separator +
    "Analogica_Prm_TipoIngressoanalogico_Ai" + separator +
    "Analogica_Hmi_AbilitaSogliaIntMax_Ai" + separator +
    "Analogica_Hmi_AbilitaSogliaIntMin_Ai" + separator +
    "Analogica_Hmi_AbilitaSogliaMax_Ai" + separator +
    "Analogica_Hmi_AbilitaSogliaMin_Ai" + separator +
    "Analogica_Hmi_NomeSoglia_IntMax_Ai" + separator +
    "Analogica_Hmi_NomeSoglia_IntMin_Ai" + separator +
    "Analogica_Hmi_NomeSoglia_Max_Ai" + separator +
    "Analogica_Hmi_NomeSoglia_Min_Ai" + separator +
    "Analogica_Hmi_ParataPresente_Ai" + separator +
    "Analogica_Hmi_SimulazioneAnalogica_AbilitaTimeout_Ai" + separator +
    "Analogica_Hmi_SimulazioneAnalogica_Attiva_Ai" + separator +
    "Analogica_Hmi_SimulazioneAnalogica_TimeoutTrascorso_Ai" + separator +
    "Analogica_Hmi_SimulazioneAnalogica_TimeoutPreset_Ai" + separator +
    "Analogica_Hmi_SimulazioneAnalogica_Valore_Ai" + separator +
    "Analogica_Allarmi_AbilitaSegnalazioneHMI_IntMax_Ai" + separator +
    "Analogica_Allarmi_AbilitaSegnalazioneHMI_IntMin_Ai" + separator +
    "Analogica_Allarmi_AbilitaSegnalazioneHMI_Maxi_Ai" + separator +
    "Analogica_Allarmi_AbilitaSegnalazioneHMI_Mini_Ai" + separator +
    "Analogica_Allarmi_AbilitaSegnalazioneHMI_OutOfRange_Ai" + separator +
    "Analogica_Allarmi_AbilitaStatoAllarmeMin_Ai" + separator +
    "Analogica_Allarmi_AbilitaStatoAllarmeOutOfRange_Ai" + separator +
    "Analogica_Allarmi_AllarmeDirezioneAllarme_IntMin_Ai" + separator +
    "Analogica_Allarmi_AllarmeDirezioneAllarme_Maxi_Ai" + separator +
    "Analogica_Allarmi_AllarmeDirezioneAllarme_Mini_Ai" + separator +
    "Analogica_Allarmi_AllarmeEnCadCiclo_IntMax_Ai" + separator +
    "Analogica_Allarmi_AllarmeEnCadCiclo_IntMin_Ai" + separator +
    "Analogica_Allarmi_AllarmeEnCadCiclo_Maxi_Ai" + separator +
    "Analogica_Allarmi_AllarmeEnCadCiclo_Mini_Ai" + separator +
    "Analogica_Allarmi_AllarmeLivelloIntMax_Ai" + separator +
    "Analogica_Allarmi_AllarmeLivelloIntMin_Ai" + separator +
    "Analogica_Allarmi_AllarmeLivelloMax_Ai" + separator +
    "Analogica_Allarmi_AllarmeLivelloMin_Ai" + separator +
    "Analogica_Allarmi_AllarmeModoResetAllarmeIntmax_Ai" + separator +
    "Analogica_Allarmi_AllarmeModoResetAllarmeIntmin_Ai" + separator +
    "Analogica_Allarmi_AllarmeModoResetAllarmeMaxi_Ai" + separator +
    "Analogica_Allarmi_AllarmeModoResetAllarmeMini_Ai" + separator +
    "Analogica_Allarmi_OutOfRangeAllarmiBT_Ai" + separator +
    "Analogica_Out_IntmaxAllarmiBT_Ai" + separator +
    "Analogica_Out_IntminAllarmiBT_Ai" + separator +
    "Analogica_Out_MaxAllarmiBT_Ai" + separator +
    "Analogica_Out_MinAllarmiBT_Ai" + separator +
    "Analogica_Rif_Attuale_AI_Valore" + separator +
    "Analogica_Rif_Inc_KpIngiresso_Ai" + separator +
    "Analogica_Rif_Inc_KpParata_Ai" + separator +
    "Analogica_Rif_Inc_Kpid_Ingresso_Ai" + separator +
    "Analogica_Rif_Inc_Kpid_Uscita_Ai" + separator +
    "Analogica_Rif_Inc_Ktrend_Ai" + separator +
    "Index_analogica_Ai";
  const row = timestamp + separator +
    v01 + separator + v02 + separator + v03 + separator + v04 + separator + v05 + separator + v06 + separator + v07 + separator + v08 + separator + v09 + separator + v10 + separator +
    v11 + separator + v12 + separator + v13 + separator + v14 + separator + v15 + separator + v16 + separator + v17 + separator + v18 + separator + v19 + separator + v20 + separator +
    v21 + separator + v22 + separator + v23 + separator + v24 + separator + v25 + separator + v26 + separator + v27 + separator + v28 + separator + v29 + separator + v30 + separator +
    v31 + separator + v32 + separator + v33 + separator + v34 + separator + v35 + separator + v36 + separator + v37 + separator + v38 + separator + v39 + separator + v40 + separator +
    v41 + separator + v42 + separator + v43 + separator + v44 + separator + v45 + separator + v46 + separator + v47 + separator + v48 + separator + v49 + separator + v50 + separator +
    v51 + separator + v52 + separator + v53 + separator + v54 + separator + v55 + separator + v56 + separator + v57 + separator + v58 + separator + v59 + separator + v60 + separator +
    v61 + separator + v62 + separator + v63 + separator + v64 + separator + v65 + separator + v66 + separator + v67 + separator + v68 + separator + v69 + separator + v70 + separator +
    v71 + separator + v72 + separator + v73 + separator + v74 + separator + v75 + separator + v76 + separator + v77 + separator + v78 + separator + v79;

  const csvContent = header + "\r\n" + row;

  // Scrivo il file CSV nella cartella 'analogica' sotto shared\\scripting
  // Percorso effettivo: ...\\[Progetto]\\shared\\scripting\\analogica\\AI_<timestamp>.csv
  const fileName = "analogica\\AI_" + timestamp + ".csv";

  const result = fileWriteSync(fileName, csvContent, "utf8");

  if (result && result.error) {
    HMIRuntime.Trace("Errore fileWriteSync su '" + fileName + "': " + result.error);
  } else {
    HMIRuntime.Trace("fileWriteSync OK: " + fileName);
  }
}
