
/*<auto-generated>
***End of Global definition area***
Changes to this comment may cause incorrect behavior during document based import.
</auto-generated>*/
export function Scroll(GestureVersoDx, GestureVersoSx) {

  let NumVistaAttuale = Tags("NumVistaAttuale");

  if (GestureVersoDx & NumVistaAttuale.Read() > 0 ){
    NumVistaAttuale.Write(NumVistaAttuale.Read() - 1);
  }
  if (GestureVersoSx & NumVistaAttuale.Read() < 4 ){
    NumVistaAttuale.Write(NumVistaAttuale.Read() + 1);
  }
}
export function DefinisciVista() {

  var i = 0;
  let TipoVista = Tags("K_TipoSottoMenu").Read();

 if (TipoVista == 0){
    if(Tags("K_NumAnalogica").Read() > 0 ){             Tags('ContenutoMenuCompleto[' + i +']').Write(Tags("K_TipoAnalogica").Read()); i++; }    
    if(Tags("K_NumMacchinaARicetta").Read() > 0 ){      Tags('ContenutoMenuCompleto[' + i +']').Write(Tags("K_TipoRicetta").Read()); i++; }    
    if(Tags("K_NumPid").Read() > 0 ){                   Tags('ContenutoMenuCompleto[' + i +']').Write(Tags("K_TipoPid").Read());  i++; }
    if(Tags("K_NumValvola").Read() > 0 ){               Tags('ContenutoMenuCompleto[' + i +']').Write(Tags("K_TipoValvola").Read()); i++;}
    if(Tags("K_NumMotore").Read() > 0 ){                Tags('ContenutoMenuCompleto[' + i +']').Write(Tags("K_TipoMotore").Read()); i++; }
    if(Tags("K_NumZona").Read() > 0 ){                  Tags('ContenutoMenuCompleto[' + i +']').Write(Tags("K_TipoZona").Read()); i++;}      
    if(Tags("K_NumSequenza").Read() > 0 ){              Tags('ContenutoMenuCompleto[' + i +']').Write(Tags("K_TipoSequenza").Read()); i++; }
    if(Tags("K_NumPortata").Read() > 0 ){               Tags('ContenutoMenuCompleto[' + i +']').Write(Tags("K_TipoPortata").Read()); i++; }
    if(Tags("K_NumParatia").Read() > 0 ){               Tags('ContenutoMenuCompleto[' + i +']').Write(Tags("K_TipoParatia").Read());  i++; }   
    if(Tags("K_NumSensore").Read() > 0 ){               Tags('ContenutoMenuCompleto[' + i +']').Write(Tags("K_TipoSensore").Read()); i++;}
    if(Tags("K_NumSegnaliMacchina").Read() > 0 ){       Tags('ContenutoMenuCompleto[' + i +']').Write(Tags("K_TipoSegnaliMacchina").Read()); i++;}
    if(Tags("K_NumSezionePastorizzatore").Read() > 0 ){ Tags('ContenutoMenuCompleto[' + i +']').Write(Tags("K_TipoSezionePastorizzatore").Read()); i++; }

  }
  if (TipoVista > 0){
    for (let IndiceVistaMenu = 0; IndiceVistaMenu < 100; IndiceVistaMenu++) {
      Tags('ContenutoMenuCompleto[' + IndiceVistaMenu +']').Write(IndiceVistaMenu + 1);
    } 
  }

//Riempio l'array della vista menu in maniera dinamica, andando a scrollare il menu completo di tutti i menu
  var IndiceArrayCompleto = Tags("NumVistaAttuale").Read() * 8;
  for (let IndiceVistaMenu = 0; IndiceVistaMenu < 8; IndiceVistaMenu++) {
    Tags('ValoreVistaMenu[' + IndiceVistaMenu +']').Write(Tags('ContenutoMenuCompleto[' + IndiceArrayCompleto +']').Read());
    IndiceArrayCompleto++; 
  } 
}
export function Visibilità() {

let K_NumMax = Tags("K_NumMaxVista");         //Numero massimo da visualizzare nel menu, scritto in apertura pagina dal k_num della vista menu

let VistaMenu0 = Tags("ValoreVistaMenu[0]");   //Leggo quanto vale la vista menu numero 0 (Locazione array)
let VistaMenu1 = Tags("ValoreVistaMenu[1]");   //Leggo quanto vale la vista menu numero 1 (Locazione array) 
let VistaMenu2 = Tags("ValoreVistaMenu[2]");   //Leggo quanto vale la vista menu numero 2 (Locazione array) 
let VistaMenu3 = Tags("ValoreVistaMenu[3]");   //Leggo quanto vale la vista menu numero 3 (Locazione array) 
let VistaMenu4 = Tags("ValoreVistaMenu[4]");   //Leggo quanto vale la vista menu numero 4 (Locazione array)
let VistaMenu5 = Tags("ValoreVistaMenu[5]");   //Leggo quanto vale la vista menu numero 5 (Locazione array)
let VistaMenu6 = Tags("ValoreVistaMenu[6]");   //Leggo quanto vale la vista menu numero 6 (Locazione array)
let VistaMenu7 = Tags("ValoreVistaMenu[7]");   //Leggo quanto vale la vista menu numero 7 (Locazione array)

Tags("VisibilVistaMenu[0]").Write(VistaMenu0.Read()<= K_NumMax.Read() & VistaMenu0.Read() > 0);    //Imposto che è visibile se è maggiore di zero ed inferiore del numero massimo
Tags("VisibilVistaMenu[1]").Write(VistaMenu1.Read()<= K_NumMax.Read() & VistaMenu1.Read() > 0);    //Imposto che è visibile se è maggiore di zero ed inferiore del numero massimo
Tags("VisibilVistaMenu[2]").Write(VistaMenu2.Read()<= K_NumMax.Read() & VistaMenu2.Read() > 0);    //Imposto che è visibile se è maggiore di zero ed inferiore del numero massimo
Tags("VisibilVistaMenu[3]").Write(VistaMenu3.Read()<= K_NumMax.Read() & VistaMenu3.Read() > 0);    //Imposto che è visibile se è maggiore di zero ed inferiore del numero massimo
Tags("VisibilVistaMenu[4]").Write(VistaMenu4.Read()<= K_NumMax.Read() & VistaMenu4.Read() > 0);    //Imposto che è visibile se è maggiore di zero ed inferiore del numero massimo
Tags("VisibilVistaMenu[5]").Write(VistaMenu5.Read()<= K_NumMax.Read() & VistaMenu5.Read() > 0);    //Imposto che è visibile se è maggiore di zero ed inferiore del numero massimo
Tags("VisibilVistaMenu[6]").Write(VistaMenu6.Read()<= K_NumMax.Read() & VistaMenu6.Read() > 0);    //Imposto che è visibile se è maggiore di zero ed inferiore del numero massimo
Tags("VisibilVistaMenu[7]").Write(VistaMenu7.Read()<= K_NumMax.Read() & VistaMenu7.Read() > 0);    //Imposto che è visibile se è maggiore di zero ed inferiore del numero massimo

Tags("Index_VistaMenu_0").Write(VistaMenu0.Read())  //Variabile intera NON ad Array utilizzata per multiplexare le viste. Sono D'appoggio.
Tags("Index_VistaMenu_1").Write(VistaMenu1.Read())  //Variabile intera NON ad Array utilizzata per multiplexare le viste. Sono D'appoggio.
Tags("Index_VistaMenu_2").Write(VistaMenu2.Read())  //Variabile intera NON ad Array utilizzata per multiplexare le viste. Sono D'appoggio.
Tags("Index_VistaMenu_3").Write(VistaMenu3.Read())  //Variabile intera NON ad Array utilizzata per multiplexare le viste. Sono D'appoggio.
Tags("Index_VistaMenu_4").Write(VistaMenu4.Read())  //Variabile intera NON ad Array utilizzata per multiplexare le viste. Sono D'appoggio.
Tags("Index_VistaMenu_5").Write(VistaMenu5.Read())  //Variabile intera NON ad Array utilizzata per multiplexare le viste. Sono D'appoggio.
Tags("Index_VistaMenu_6").Write(VistaMenu6.Read())  //Variabile intera NON ad Array utilizzata per multiplexare le viste. Sono D'appoggio.
Tags("Index_VistaMenu_7").Write(VistaMenu7.Read())  //Variabile intera NON ad Array utilizzata per multiplexare le viste. Sono D'appoggio.

// ******************* GESTIONE DELL'UNITA' DI MISURA DA VISUALIZZARE NEL MENU *********************************

let ValoreUmVista0          = Tags("ContenutoMenu[0]");             //Punto la variabile in cui scrivere l'unità di misura
let ValoreUmVista1          = Tags("ContenutoMenu[1]");             //Punto la variabile in cui scrivere l'unità di misura
let ValoreUmVista2          = Tags("ContenutoMenu[2]");             //Punto la variabile in cui scrivere l'unità di misura
let ValoreUmVista3          = Tags("ContenutoMenu[3]");             //Punto la variabile in cui scrivere l'unità di misura
let ValoreUmVista4          = Tags("ContenutoMenu[4]");             //Punto la variabile in cui scrivere l'unità di misura
let ValoreUmVista5          = Tags("ContenutoMenu[5]");             //Punto la variabile in cui scrivere l'unità di misura
let ValoreUmVista6          = Tags("ContenutoMenu[6]");             //Punto la variabile in cui scrivere l'unità di misura
let ValoreUmVista7          = Tags("ContenutoMenu[7]");             //Punto la variabile in cui scrivere l'unità di misura
let K_TipoAttuale           = Tags("K_TipoSottoMenu").Read();       //Leggo in che vista sono
let K_TipoAnalog            = Tags("K_TipoAnalogica").Read();       //Leggo il valore della costante analogica
let K_TipoPid               = Tags("K_TipoPid").Read();             //Leggo il valore della costante pid
let K_TipoValvola           = Tags("K_TipoValvola").Read();         //Leggo il valore della costante valvola
let K_TipoSequenza          = Tags("K_TipoSequenza").Read();        //Leggo il valore della costante sequenza
let K_TipoZona              = Tags("K_TipoZona").Read();            //Leggo il valore della costante zona
let K_TipoMotore            = Tags("K_TipoMotore").Read();          //Leggo il valore della costante motore
let K_TipoPortata           = Tags("K_TipoPortata").Read();         //Leggo il valore della costante portata
let K_TipoComunicazioneS7   = Tags("K_TipoComunicazioneS7").Read(); //Leggo il valore della costante comunicazioneS7
let K_TipoRicetta           = Tags("K_TipoRicetta").Read();         //Leggo il valore della costante ricetta
let K_TipoSegnaliMacchina   = Tags("K_TipoSegnaliMacchina").Read(); //Leggo il valore della costante ricetta

var UmCodeVista0, UmCodeVista1, UmCodeVista2, UmCodeVista3, UmCodeVista4, UmCodeVista5, UmCodeVista6, UmCodeVista7;
var AbilitaUm = 0; //Se stiamo visualizzando un'unità di misura lo abilitiamo.

switch (K_TipoAttuale) {    //Scegliamo in base alla vista visualizzata cosa mostrare nell'anteprima
  case K_TipoAnalog:
    UmCodeVista0 = '' + Tags("MenuAnalogica_Unità di misuraVista0").Read();   //Questa variabile è indicizzata e nel caso delle analogiche 
    UmCodeVista1 = '' + Tags("MenuAnalogica_Unità di misuraVista1").Read();   //mostriamo come anteprima l'unità di misura
    UmCodeVista2 = '' + Tags("MenuAnalogica_Unità di misuraVista2").Read();
    UmCodeVista3 = '' + Tags("MenuAnalogica_Unità di misuraVista3").Read();
    UmCodeVista4 = '' + Tags("MenuAnalogica_Unità di misuraVista4").Read();
    UmCodeVista5 = '' + Tags("MenuAnalogica_Unità di misuraVista5").Read();
    UmCodeVista6 = '' + Tags("MenuAnalogica_Unità di misuraVista6").Read();
    UmCodeVista7 = '' + Tags("MenuAnalogica_Unità di misuraVista7").Read();
    AbilitaUm = 1;
  break;
  case K_TipoPid:
    UmCodeVista0 = '' + Tags("MenuPid_Unità di misuraVista0").Read();   //Questa variabile è indicizzata e nel caso del pid 
    UmCodeVista1 = '' + Tags("MenuPid_Unità di misuraVista1").Read();   //mostriamo come anteprima l'unità di misura
    UmCodeVista2 = '' + Tags("MenuPid_Unità di misuraVista2").Read();
    UmCodeVista3 = '' + Tags("MenuPid_Unità di misuraVista3").Read();
    UmCodeVista4 = '' + Tags("MenuPid_Unità di misuraVista4").Read();
    UmCodeVista5 = '' + Tags("MenuPid_Unità di misuraVista5").Read();
    UmCodeVista6 = '' + Tags("MenuPid_Unità di misuraVista6").Read();
    UmCodeVista7 = '' + Tags("MenuPid_Unità di misuraVista7").Read();
    AbilitaUm = 1;
  break;
  case K_TipoValvola:
    UmCodeVista0 = Tags("MenuValvola_StatoUscita0").Read();   //Questa variabile è indicizzata e nel caso della valvola 
    UmCodeVista1 = Tags("MenuValvola_StatoUscita1").Read();   //mostriamo come anteprima lo stato di uscita
    UmCodeVista2 = Tags("MenuValvola_StatoUscita2").Read();
    UmCodeVista3 = Tags("MenuValvola_StatoUscita3").Read();
    UmCodeVista4 = Tags("MenuValvola_StatoUscita4").Read();
    UmCodeVista5 = Tags("MenuValvola_StatoUscita5").Read();
    UmCodeVista6 = Tags("MenuValvola_StatoUscita6").Read();
    UmCodeVista7 = Tags("MenuValvola_StatoUscita7").Read();
  break;
  case K_TipoSequenza:
    UmCodeVista0 = Tags("MenuSequenza_Stato0").Read();   //Questa variabile è indicizzata e nel caso della sequenza 
    UmCodeVista1 = Tags("MenuSequenza_Stato1").Read();   //mostriamo come anteprima lo stato della sequenza
    UmCodeVista2 = Tags("MenuSequenza_Stato2").Read();
    UmCodeVista3 = Tags("MenuSequenza_Stato3").Read();
    UmCodeVista4 = Tags("MenuSequenza_Stato4").Read();
    UmCodeVista5 = Tags("MenuSequenza_Stato5").Read();
    UmCodeVista6 = Tags("MenuSequenza_Stato6").Read();
    UmCodeVista7 = Tags("MenuSequenza_Stato7").Read();
  break;
  case K_TipoZona:
    UmCodeVista0 = Tags("MenuZona_Stato0").Read();   //Questa variabile è indicizzata e nel caso della sequenza 
    UmCodeVista1 = Tags("MenuZona_Stato1").Read();   //mostriamo come anteprima lo stato della sequenza
    UmCodeVista2 = Tags("MenuZona_Stato2").Read();
    UmCodeVista3 = Tags("MenuZona_Stato3").Read();
    UmCodeVista4 = Tags("MenuZona_Stato4").Read();
    UmCodeVista5 = Tags("MenuZona_Stato5").Read();
    UmCodeVista6 = Tags("MenuZona_Stato6").Read();
    UmCodeVista7 = Tags("MenuZona_Stato7").Read();
  break;
  case K_TipoMotore:
    UmCodeVista0 = Tags("MenuMotore_Stato0").Read();   //Questa variabile è indicizzata e nel caso della sequenza 
    UmCodeVista1 = Tags("MenuMotore_Stato1").Read();   //mostriamo come anteprima lo stato del motore
    UmCodeVista2 = Tags("MenuMotore_Stato2").Read();
    UmCodeVista3 = Tags("MenuMotore_Stato3").Read();
    UmCodeVista4 = Tags("MenuMotore_Stato4").Read();
    UmCodeVista5 = Tags("MenuMotore_Stato5").Read();
    UmCodeVista6 = Tags("MenuMotore_Stato6").Read();
    UmCodeVista7 = Tags("MenuMotore_Stato7").Read();
  break;
  case K_TipoPortata:
    UmCodeVista0 = K_TipoPortata;   //Nel caso della portata nell'anteprima mostriamo semplicemente il simbolo della portata
    UmCodeVista1 = K_TipoPortata;
    UmCodeVista2 = K_TipoPortata;
    UmCodeVista3 = K_TipoPortata;
    UmCodeVista4 = K_TipoPortata;
    UmCodeVista5 = K_TipoPortata;
    UmCodeVista6 = K_TipoPortata;
    UmCodeVista7 = K_TipoPortata;
  break;
case K_TipoSegnaliMacchina:
    UmCodeVista0 = K_TipoSegnaliMacchina;   //Nel caso dei segnali macchina nell'anteprima mostriamo semplicemente il simbolo dei segali macchina
    UmCodeVista1 = K_TipoSegnaliMacchina;
    UmCodeVista2 = K_TipoSegnaliMacchina;
    UmCodeVista3 = K_TipoSegnaliMacchina;
    UmCodeVista4 = K_TipoSegnaliMacchina;
    UmCodeVista5 = K_TipoSegnaliMacchina;
    UmCodeVista6 = K_TipoSegnaliMacchina;
    UmCodeVista7 = K_TipoSegnaliMacchina;
  break;
  case K_TipoComunicazioneS7:
    UmCodeVista0 = K_TipoComunicazioneS7;   //Nel caso della portata nell'anteprima mostriamo semplicemente il simbolo della comunicazione
    UmCodeVista1 = K_TipoComunicazioneS7;
    UmCodeVista2 = K_TipoComunicazioneS7;
    UmCodeVista3 = K_TipoComunicazioneS7;
    UmCodeVista4 = K_TipoComunicazioneS7;
    UmCodeVista5 = K_TipoComunicazioneS7;
    UmCodeVista6 = K_TipoComunicazioneS7;
    UmCodeVista7 = K_TipoComunicazioneS7;
  break;
  case K_TipoRicetta:
    UmCodeVista0 = Tags("MenuRicetta_CodiceMacchinario0").Read();   //Nel caso della portata nell'anteprima mostriamo semplicemente il simbolo della comunicazione
    UmCodeVista1 = Tags("MenuRicetta_CodiceMacchinario1").Read();
    UmCodeVista2 = Tags("MenuRicetta_CodiceMacchinario2").Read();
    UmCodeVista3 = Tags("MenuRicetta_CodiceMacchinario3").Read();
    UmCodeVista4 = Tags("MenuRicetta_CodiceMacchinario4").Read();
    UmCodeVista5 = Tags("MenuRicetta_CodiceMacchinario5").Read();
    UmCodeVista6 = Tags("MenuRicetta_CodiceMacchinario6").Read();
    UmCodeVista7 = Tags("MenuRicetta_CodiceMacchinario7").Read();
  break;
  default:
    UmCodeVista0 = '';
    UmCodeVista1 = '';
    UmCodeVista2 = '';
    UmCodeVista3 = '';
    UmCodeVista4 = '';
    UmCodeVista5 = '';
    UmCodeVista6 = '';
    UmCodeVista7 = '';
  break;
}
  if(AbilitaUm == 1){
    ValoreUmVista0.Write(parseInt(UmCodeVista0[0]));
    ValoreUmVista1.Write(parseInt(UmCodeVista1[0]));
    ValoreUmVista2.Write(parseInt(UmCodeVista2[0]));
    ValoreUmVista3.Write(parseInt(UmCodeVista3[0]));
    ValoreUmVista4.Write(parseInt(UmCodeVista4[0]));
    ValoreUmVista5.Write(parseInt(UmCodeVista5[0]));
    ValoreUmVista6.Write(parseInt(UmCodeVista6[0]));
    ValoreUmVista7.Write(parseInt(UmCodeVista7[0]));
  }
  if(AbilitaUm == 0){
    ValoreUmVista0.Write(UmCodeVista0);
    ValoreUmVista1.Write(UmCodeVista1);
    ValoreUmVista2.Write(UmCodeVista2);
    ValoreUmVista3.Write(UmCodeVista3);
    ValoreUmVista4.Write(UmCodeVista4);
    ValoreUmVista5.Write(UmCodeVista5);
    ValoreUmVista6.Write(UmCodeVista6);
    ValoreUmVista7.Write(UmCodeVista7);
  }
}
export function ResettaVista() {



    for (let IndiceVistaMenu = 0; IndiceVistaMenu < 100; IndiceVistaMenu++) {
      Tags('ContenutoMenuCompleto[' + IndiceVistaMenu +']').Write(0);
    } 

    Tags("VisibilVistaMenu[0]").Write(0);    //Imposto che è visibile se è maggiore di zero ed inferiore del numero massimo
    Tags("VisibilVistaMenu[1]").Write(0);    //Imposto che è visibile se è maggiore di zero ed inferiore del numero massimo
    Tags("VisibilVistaMenu[2]").Write(0);    //Imposto che è visibile se è maggiore di zero ed inferiore del numero massimo
    Tags("VisibilVistaMenu[3]").Write(0);    //Imposto che è visibile se è maggiore di zero ed inferiore del numero massimo
    Tags("VisibilVistaMenu[4]").Write(0);    //Imposto che è visibile se è maggiore di zero ed inferiore del numero massimo
    Tags("VisibilVistaMenu[5]").Write(0);    //Imposto che è visibile se è maggiore di zero ed inferiore del numero massimo
    Tags("VisibilVistaMenu[6]").Write(0);    //Imposto che è visibile se è maggiore di zero ed inferiore del numero massimo
    Tags("VisibilVistaMenu[7]").Write(0);    //Imposto che è visibile se è maggiore di zero ed inferiore del numero massimo

}
