
/*<auto-generated>
***End of Global definition area***
Changes to this comment may cause incorrect behavior during document based import.
</auto-generated>*/
/**
Restituisce il valore multiplexato nella "RadiceVaribaile"_Multiplex

*/
export function Multiplexing(Indice, RadiceVariabile) {
  //In indice immetiamo il numero che attualmente intendiamo visualizzare,
  //dobbiamo aver creato una varibaile per ogni numero che vogliamo visualizzare
  //In base al numero passato la funzione va a leggere la variabile con quel numero finale
  
  Tags(RadiceVariabile + "_Multiplex").Write(Tags(RadiceVariabile + "_" + Indice).Read());

}
