FUNCTION "Motore_PompaVuoto" : Void
{ S7_Optimized_Access := 'TRUE' }
VERSION : 0.1

BEGIN
	REGION Motore_PompaVuoto
		REGION Ingressi
		END_REGION ;
		REGION Gestione
			"GestMotore"(K_Motore := "K_Motore_PompaVuoto",
			             K_TipoMotore := "K_TipoMotore_InverterSiemens",
			             K_Zona := "K_Zona_Generale");
		END_REGION ;
		REGION Uscite
		END_REGION ;
	END_REGION ;
END_FUNCTION
