FUNCTION "Motore_Sitronic" : Void
{ S7_Optimized_Access := 'TRUE' }
VERSION : 0.1

BEGIN
	REGION Motore_Sitronic
		REGION Ingressi
		END_REGION ;
		REGION Gestione
			"GestMotore"(K_Motore := "K_Motore_Sitronic",
			             K_TipoMotore := "K_TipoMotore_InverterSiemens",
			             K_Zona := "K_Zona_MagazzinoPalette");
		END_REGION ;
		REGION Uscite
		END_REGION ;
	END_REGION ;
END_FUNCTION
